# Generated by Django 5.1.4 on 2024-12-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransfer',
            name='download_link',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
